// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTGNyZlEmEzWoTr1YDQlTqIBs3z8__GKA',
    appId: '1:315747135771:web:be42e9f18bf1e0ec0363be',
    messagingSenderId: '315747135771',
    projectId: 'exam-655bd',
    authDomain: 'exam-655bd.firebaseapp.com',
    storageBucket: 'exam-655bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUF-lMsSD9xaPhmsZaodf1ShF9oqF8mDs',
    appId: '1:315747135771:android:0c70da9b3f37561d0363be',
    messagingSenderId: '315747135771',
    projectId: 'exam-655bd',
    storageBucket: 'exam-655bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB92x2oWMfJ1lSFjOZK_1nih0YeEJ6vsJ0',
    appId: '1:315747135771:ios:18281240b7c6cb210363be',
    messagingSenderId: '315747135771',
    projectId: 'exam-655bd',
    storageBucket: 'exam-655bd.appspot.com',
    iosBundleId: 'com.example.advFinalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB92x2oWMfJ1lSFjOZK_1nih0YeEJ6vsJ0',
    appId: '1:315747135771:ios:18281240b7c6cb210363be',
    messagingSenderId: '315747135771',
    projectId: 'exam-655bd',
    storageBucket: 'exam-655bd.appspot.com',
    iosBundleId: 'com.example.advFinalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTGNyZlEmEzWoTr1YDQlTqIBs3z8__GKA',
    appId: '1:315747135771:web:2e651c0ba3b445e20363be',
    messagingSenderId: '315747135771',
    projectId: 'exam-655bd',
    authDomain: 'exam-655bd.firebaseapp.com',
    storageBucket: 'exam-655bd.appspot.com',
  );
}
